"""Helper script for article POC"""

#!/usr/bin/python3
import http.server
import socketserver

class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Sending an '200 OK' response
        self.send_response(200)
        # Setting the header
        self.send_header("Content-type", "text/html")
        self.end_headers()
        # Some custom HTML code, possibly generated by another function
        html = f"<h1>Hello c0nt4in3r!</h1>"
        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))
        return
if __name__=='__main__':

    # Create an object of the above class
    HandlerObject = MyHttpRequestHandler
    my_server = socketserver.TCPServer(("", 8080), HandlerObject)
    # Star the server
    my_server.serve_forever()
